### ISSUE TITLE
Safari and Chrome Booksmark

### ISSUE THREAD

**Issue by ammannit** [hhorn76/JAMF#1]
Is there any option to create folder in Safari and Chrome? See Screenshot
<img width="586" alt="Bildschirmfoto 2019-07-28 um 15 50 06" src="https://user-images.githubusercontent.com/50989557/62007578-66fe8600-b14f-11e9-97b6-0f74670254bc.png">
<img width="616" alt="Bildschirmfoto 2019-07-28 um 15 47 12" src="https://user-images.githubusercontent.com/50989557/62007579-66fe8600-b14f-11e9-8dc2-326c963c32b9.png">

**Comment by hhorn76** [comment]
Unfortunately this script does not work for macOS 10.15 Catalina anymore. Apple has restricted the access to the ~/Library/Safari folder.
